### ISSUE TITLE
ToDo list for migration from gitlab

### ISSUE THREAD

**Issue by erciccione** [monero-project/monero-site#894]
We are migrating the monero-site repository from [Gitlab](https://repo.getmonero.org/monero-project/monero-site) to this repository. See discussion in https://github.com/monero-project/meta/issues/236.

This is a todo list of what needs to be done to complete the migration:

- [x] Clean old issues from this repo
- [x] Import issue labels
- [x] import commits from Gitlab
- [x] Import issues
- [x] import pull requests
- [ ] Add contributors with triage powers

~~**Please do not use this repository until the migration is completed.**~~  
Everything has been migrated. Feel free to use the repo, this issue will be closed when the announcement of the migration (#929) is published.

**Comment by erciccione** [comment]
Issues imported and labelled.

Waiting for the repository to be syncronized with the master on gitlab before asking people to migrate their merge requests (https://repo.getmonero.org/monero-project/monero-site/-/merge_requests) to avoid accidental rebases against an outdated master.

**Comment by erciccione** [comment]
Everything was migrated, expect some merge requests where the input of the original opener is needed. So, i think we can consider the migration completed and this issue resolved. I also [posted an update on Reddit](https://www.reddit.com/r/Monero/comments/g463jj/getmoneroorg_updated_migration_to_github_new_faq/).

I asked for people interested in having triage permissions on this repo, but got no answer yet. Those permissions can be edited anytime, so it's definitely not a stopper.
